language: go

sudo: required

env:
  - HOME=/home/travis

services:
  - docker

go:
  - "1.11"

go_import_path: github.com/IBM/multi-cluster-app-dispatcher

install:
  - go get -u golang.org/x/lint/golint

before_script:
  - export TEST_LOG_LEVEL=4

script:
#  - make
  - make mcad-controller
  - make run-test
  # Process 'make images' when NOT a pull request
  - 'if [ "$TRAVIS_PULL_REQUEST"  = "false" ]; then make images; fi'
  # Process 'make images' when running as a pull request
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then unset dockerhub_repository && make images; fi'
  # Process 'make push-images' when NOT a pull request
  - 'if [ "$TRAVIS_PULL_REQUEST"  = "false" ]; then make push-images; fi'
  - make run-e2e
