language: go

sudo: required

env:
  - HOME=/home/travis

services:
  - docker

go:
  - "1.11"

go_import_path: github.com/IBM/multi-cluster-app-dispatcher

install:
  - go get -u golang.org/x/lint/golint

before_script:
  - export TEST_LOG_LEVEL=4

script:
#  - make
  - make mcad-controller
  - make run-test
  - make images
  - make push-images
  - make run-e2e
